### ISSUE TITLE
Code coverage for Apex classes less than 75% - Reopen(#197)

### ISSUE THREAD

**Issue by daiyaharsh90** [watson-developer-cloud/salesforce-sdk#201]
Hello lpation10,

I work with posolutionez (Patrick) and we deployed the fix to our sandbox but there are still some classes which fall below the 75% threshold.

Following are the classes-
```
IBMWatsonDynamicResponseModel - 0%
IBMWatsonIAMToken - 60%
IBMWatsonICP4DToken - 73%
IBMWatsonICP4DTokenResponse - 5%
IBMWatsonNoauthAuthenticator - 25%
IBMWatsonResponseModel - 46%
IBMWatsonService - 73%
```
We are leveraging Watson Assistant and NLU part of the SDK but due to dependency between the classes above mentioned classes are also needed. When we deploy code from Sandbox to Stage and Production all classes need to have a minimum of 75% coverage it doesn't look for the whole SDK coverage. Please advice.

_Originally posted by @daiyaharsh90 in https://github.com/watson-developer-cloud/salesforce-sdk/issues/197#issuecomment-527637083_

**Comment by germanattanasio** [comment]
Hi @daiyaharsh90, The maintainer is on vacation until next. Can you wait until he is back?

You can also add a few tets for the classes in a PR and I will be happy to review and merge it

**Comment by lpatino10** [comment]
Hey @daiyaharsh90, I was under the impression that you just needed a total code coverage >75% to deploy to production orgs, so sorry about that.

I'm back now I'll report back here when it's up.

**Comment by lpatino10** [comment]
@daiyaharsh90 the issue should now be resolved fully in the latest version of `master` ([v4.4.4](https://github.com/watson-developer-cloud/salesforce-sdk/releases/tag/v4.4.4)).

All classes now have at least 75% coverage.

**Comment by daiyaharsh90** [comment]
@lpatino10 We still see 2 classes that are under 75% code coverage, Thank you for all your help so far.

IBMWatsonNoauthAuthenticator - 25% (Lines 1/4)
IBMWatsonResponseModel - 46% (Lines 12/26)

**Comment by daiyaharsh90** [comment]
@lpatino10 Apologies, it seems we have the coverage, it was probably an old test suite we ran. Thank you for helping us!
We are good with code coverage now

**Comment by lpatino10** [comment]
Great to hear!
